### PR TITLE
Create Readme update

### PR DESCRIPTION
**Pull request by kodeblacc**
More info on readme added

### CODE REVIEW

**Comment by veniosg** [comment]
Hey, thanks for the contribution (and excuse the random dude commenting, I deleted it since). 
FWIW this looks like a stray file and not an update on README.md. Additionally this text should probably be part of the gh-pages branch that houses the website (meant to be more of a user-facing info sheet) rather than the readme which is more geared towards developers.

**Comment by kodeblacc** [comment]
Oh okay, my mistake, prolly I shouldn't have used the term an update on readme. I practically did a make over to make it more informative to other people. Anyway thanks

**Comment by veniosg** [comment]
I'll close this PR but feel free to create one for the website! Thanks :)

**Comment by kodeblacc** [comment]
Alright I'll. I'm still getting used to open source communities.

How can I create a PR for an updated readme on the website

**Comment by veniosg** [comment]
Hey, I believe switching to the gh-pages branch, updating the website’s index.html and opening a PR for that branch would do the trick. That being said, much of the same info is probably already in there. Have a look here https://veniosg.github.io/Dir to see the current version.

**Pull request closed without merging**
